#!/bin/bash 

if [ "$1" == "sup" ]; then 
    nvim ~/Notes/mbahng-com/STEM/Data_Science/Supervised_Learning/Supervised_Learning.tex
fi
if [ "$1" == "deep" ]; then 
    nvim ~/Notes/mbahng-com/STEM/Data_Science/Deep_Learning/Deep_Learning.tex
fi 
if [ "$1" == "linalg" ]; then 
    nvim ~/Notes/mbahng-com/STEM/Data_Science/Supervised_Learning/Supervised_Learning.tex
fi 
if [ "$1" == "nlp" ]; then 
    nvim ~/Notes/mbahng-com/STEM/Data_Science/Supervised_Learning/Supervised_Learning.tex
fi 
if [ "$1" == "cv" ]; then 
    nvim ~/Notes/mbahng-com/STEM/Data_Science/Supervised_Learning/Supervised_Learning.tex
fi 
if [ "$1" == "real" ]; then 
    nvim ~/Notes/mbahng-com/STEM/Data_Science/Supervised_Learning/Supervised_Learning.tex
fi 
if [ "$1" == "bayes" ]; then 
    nvim ~/Notes/mbahng-com/STEM/Data_Science/Supervised_Learning/Supervised_Learning.tex
fi 
if [ "$1" == "stats" ]; then 
    nvim ~/Notes/mbahng-com/STEM/Data_Science/Supervised_Learning/Supervised_Learning.tex
fi 
