#!/bin/bash 

STEM=~/Notes/mbahng-com/STEM
MATH="${STEM}/Math"
STATISTICS="${STEM}/Statistics"
COMPUTER_SCIENCE="${STEM}/Computer_Science"
NATURAL_SCIENCES="${STEM}/Natural_Sciences"

BUSINESS_FINANCE=~/Notes/mbahng-com/Business_Finance

HUMANITIES=~/Notes/mbahng-com/Humanities
HISTORY=${HUMANITIES}/History

case "$1" in 
  "resume")
    cd ~/Notes/resume
    ;; 
  "meso")
    cd "${HISTORY}/Mesopotamia"
    ;; 
  "egypt")
    cd "${HISTORY}/Egypt"
    ;; 
  "china")
    cd "${HISTORY}/China"
    ;; 
  "india")
    cd "${HISTORY}/India"
    ;; 
  "persia")
    cd "${HISTORY}/Persia"
    ;; 
  "greeks")
    cd "${HISTORY}/Greeks"
    ;; 
  "romans")
    cd "${HISTORY}/Romans"
    ;; 
  "middle")
    cd "${HISTORY}/Middle"
    ;; 
  "early")
    cd "${HISTORY}/Early_Modern"
    ;; 
  "late")
    cd "${HISTORY}/Late_Modern"
    ;; 
  "post")
    cd "${HISTORY}/Postmodern"
    ;; 
  "quant")
    cd "${BUSINESS_FINANCE}/Quantitative_Finance"
    ;; 
  "fund")
    cd "${BUSINESS_FINANCE}/Fundamental_Investing"
    ;; 
  "macro")
    cd "${BUSINESS_FINANCE}/Macroeconomics"
    ;; 
  "micro")
    cd "${BUSINESS_FINANCE}/Microeconomics"
    ;; 
  "qm")
    cd "${NATURAL_SCIENCES}/Quantum_Mechanics"
    ;; 
  "ml")
    cd "${STATISTICS}/Machine_Learning"
    ;; 
  "deep")
    cd "${STATISTICS}/Deep_Learning"
    ;; 
  "rein")
    cd "${STATISTICS}/Reinforcement_Learning"
    ;; 
  "info")
    cd "${STATISTICS}/Information_Theory_Signal_Processing"
    ;; 
  "optim")
    cd "${STATISTICS}/Sampling_and_Optimization"
    ;; 
  "freq")
    cd "${STATISTICS}/Frequentist_Statistics"
    ;; 
  "bayes")
    cd "${STATISTICS}/Bayesian_Statistics"
    ;; 
  "cv")
    cd "${STATISTICS}/Computer_Vision"
    ;; 
  "nlp")
    cd "${STATISTICS}/Natural_Language_Processing"
    ;; 
  "alg")
    cd "${MATH}/Abstract_Algebra"
    ;;
  "algtop")
    cd "${MATH}/Algebraic_Topology"
    ;;
  "complex")
    cd "${MATH}/Complex_Analysis"
    ;;
  "concentration")
    cd "${MATH}/Concentration_of_Measure"
    ;;
  "diffgeo")
    cd "${MATH}/Differential_Geometry"
    ;;
  "functional")
    cd "${MATH}/Functional_Analysis"
    ;;
  "linalg")
    cd "${MATH}/Linear_Algebra"
    ;;
  "measure")
    cd "${MATH}/Measure_Theory"
    ;;
  "multi")
    cd "${MATH}/Multivariate_Calculus"
    ;;
  "number")
    cd "${MATH}/Number_Theory"
    ;;
  "ode")
    cd "${MATH}/Ordinary_Differential_Equations"
    ;;
  "pde")
    cd "${MATH}/Partial_Differential_Equations"
    ;;
  "top")
    cd "${MATH}/Point_Set_Topology"
    ;;
  "prob")
    cd "${MATH}/Probability_Theory"
    ;;
  "real")
    cd "${MATH}/Real_Analysis"
    ;;
  "smooth")
    cd "${MATH}/Smooth_Manifolds"
    ;;
  "stoch")
    cd "${MATH}/Stochastic_Processes"
    ;;
  "linux")
    cd "${COMPUTER_SCIENCE}/Linux"
    ;;
  "block")
    cd "${COMPUTER_SCIENCE}/Blockchain"
    ;;
  "qcomp")
    cd "${COMPUTER_SCIENCE}/Quantum_Computing"
    ;;
  "dsa")
    cd "${COMPUTER_SCIENCE}/Data_Structures_Algorithms"
    ;;
  "system")
    cd "${COMPUTER_SCIENCE}/Systems"
esac
nvim paper.tex
